[versions]
# Platforms
minecraft = "1.21.8-R0.1-SNAPSHOT"

# Minecraft Plugins
worldedit = "7.3.16"
fawe = "2.14.0"

[libraries]
# Platform
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "minecraft" }

# Minecraft Plugins
worldeditCore = { group = "com.sk89q.worldedit", name = "worldedit-core", version.ref = "worldedit" }
fastasyncworldeditCore = { group = "com.fastasyncworldedit", name = "FastAsyncWorldEdit-Core", version.ref = "fawe" }
